/*
 * timer0_config.h
 *
 * Created: 10/27/2023 10:39:02 AM
 *  Author: Mina
 */ 


#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_


#define TIMER0_NORMAL_MODE				0
#define TIMER0_CTC_MODE					1
#define TIMER0_PWM_PHASE_CORRECT		2
#define TIMER0_FAST_PWM					3

typedef enum{
	NO_CLOCK_SOURCE,
	CLOCK_NO_PRESCALER,
	CLOCK_WITH_PRESCALER_8,
	CLOCK_WITH_PRESCALER_64,
	CLOCK_WITH_PRESCALER_256,
	CLOCK_WITH_PRESCALER_1024,
	CLOCK_EXTERNAL_FALLING_EDGE,
	CLOCK_EXTERNAL_RISING_EDGE,
}timer0_CS_t;

typedef enum{
	NORMAL_OC0_DISCONNECTED,
	TOGGLE_OC0_ON_COMPARE_MATCH,
	CLEAR_OC0_ON_COMPARE_MATCH,
	SET_OC0_ON_COMPARE_MATCH,
}timer0_CTC_CMO_t;

typedef enum{
	NO_ACTION_OC0_DISCONNECTED,
	PULSE_NON_INVERTED_HIGH_START_CLEAR_OC0,
	PULSE_INVERTED_LOW_START_SET_OC0,
}timer0_PWM_CMO_t;

#define OC0_DISABLE		0x00
#define OC0_ENABLE		0x01

/****************CONFIGURABLE SETTING****************************/
#define TIMER0_WORKING_MODE				TIMER0_CTC_MODE

#if TIMER0_NORMAL_MODE==TIMER0_WORKING_MODE
	#define TIMER0_INITIAL_REG_VALUE		87
	#define TIMER0_OVERFLOWS_NEEDED			1
	#define TIMER0_PRESCALER_MODE			CLOCK_WITH_PRESCALER_1024
#elif TIMER0_CTC_MODE==TIMER0_WORKING_MODE
	#define TIMER0_INITIAL_OCR_VALUE		250
	#define TIMER0_OCR_OVERFLOWS_NEEDED		1
	#define TIMER0_PRESCALER_MODE			CLOCK_WITH_PRESCALER_64
	#define OC0_PIN_OUTPUT_ENABLE			OC0_ENABLE
	#define TIMER0_CTC_OUTPUT_MODE			TOGGLE_OC0_ON_COMPARE_MATCH
#elif TIMER0_FAST_PWM==TIMER0_WORKING_MODE || TIMER0_PWM_PHASE_CORRECT==TIMER0_WORKING_MODE
	#define TIMER0_PWM_OCR_VALUE			50
	#define TIMER0_PRESCALER_MODE			CLOCK_WITH_PRESCALER_1024
	#define TIMER0_PWM_OUTPUT_MODE			PULSE_NON_INVERTED_HIGH_START_CLEAR_OC0
#endif
/****************CONFIGURABLE SETTING****************************/

#endif /* TIMER0_CONFIG_H_ */